services:
  aimms:
    image: aimms:${AIMMS_VERSION}
    build:
      context: .
      args:
        AIMMS_VERSION: ${AIMMS_VERSION}
    volumes:
      # mounting to /model such that the model is available in the container and the logs are written to the host
      - ./testing/AimmsUnitTestTest:/model
      # this is the path to the AIMMS folder containing the license file so for example: C:/ProgramData/AIMMS required to run aimms
      - C:/ProgramData/AIMMS:/data

    # run AimmsCmd with the following arguments
    entrypoint: ["/usr/local/Aimms/Bin/AimmsCmd"]

    # don't forget to change the path to the model file
    command: ["--aimms-root-path", "/data", "--run-only", "${AIMMS_PROCEDURE}", "/model/${AIMMS_PROJECT_NAME}"]
    